name: Gromacs

on:
  push:
    branches:
      - master
    paths:
      - 'gromacs/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'gromacs/**'

env:
  GROMACS_IMAGE_NAME: gromacs-2020

  DOCKERHUB_REPO: hpc-app-container
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  gromacs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build image
        run: docker build . --file "gromacs/gromacs-2020.Dockerfile" --tag $GROMACS_IMAGE_NAME

  gromacs:
    needs: gromacs-test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file "gromacs/gromacs-2020.Dockerfile" --tag $GROMACS_IMAGE_NAME

      - name: Log into registry
        run: echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USER --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$DOCKERHUB_USER/$DOCKERHUB_REPO
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$GROMACS_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $GROMACS_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
